name: Maven CI

on:
  push:
    branches:
      - main  # Die Pipeline wird bei einem Push auf den `main`-Branch ausgelöst
  pull_request:
    branches:
      - main  # Auch bei Pull Requests auf `main`

jobs:
  test:
    runs-on: ubuntu-latest  # Der Job läuft auf einer Ubuntu-Maschine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'

      - name: Build and run tests
        run: mvn clean install  # Tests ausführen

      - name: Generate surefire report
        run: mvn surefire-report:report  # Report generieren

      - name: Upload surefire report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: surefire-report
          path: target/site/surefire-report.html  # Der Report wird als Artifact gespeichert
